apiVersion: v1
kind: Pod
metadata:
  name: config-test
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: config
      mountPath: "/etc/config"
    - name: secret
      mountPath: "/etc/secret"
  volumes:
  - name: config
    configMap:
      name: my-config
  - name: secret
    secret:
      secretName: my-secret